version: '3'

services:
    nginx:
        image: nginx:mainline-alpine
        
    client:
        build: ./client
        ports:
            - 8080:8080
    server:
        build: ./server
        ports:
            - 8081:8081

